-- MySQL Script generated by MySQL Workbench
-- Sun Jul 24 20:29:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema emf_products_example_app_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emf_products_example_app_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emf_products_example_app_test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `emf_products_example_app_test`;

-- -----------------------------------------------------
-- Table `emf_products_example_app_test`.`emf_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emf_products_example_app_test`.`emf_category`
(
    `id`        INT UNSIGNED        NOT NULL AUTO_INCREMENT,
    `title`     VARCHAR(255)        NOT NULL,
    `active`    TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    `parent_id` INT UNSIGNED        NULL     DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_emf_category_emf_category1_idx` (`parent_id` ASC) VISIBLE,
    CONSTRAINT `fk_emf_category_emf_category1`
        FOREIGN KEY (`parent_id`)
            REFERENCES `emf_products_example_app_test`.`emf_category` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emf_products_example_app_test`.`emf_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emf_products_example_app_test`.`emf_product`
(
    `id`              INT UNSIGNED   NOT NULL AUTO_INCREMENT,
    `title`           VARCHAR(255)   NOT NULL,
    `description`     TEXT           NULL,
    `price`           DECIMAL(10, 2) NULL,
    `image_1`         VARCHAR(255)   NULL,
    `image_2`         VARCHAR(255)   NULL,
    `image_3`         VARCHAR(255)   NULL,
    `created_at`      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `emf_category_id` INT UNSIGNED   NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_emf_product_emf_category_idx` (`emf_category_id` ASC) VISIBLE,
    INDEX `created_at_idx` (`created_at` ASC) VISIBLE,
    INDEX `updated_at_idx` (`updated_at` ASC) VISIBLE,
    CONSTRAINT `fk_emf_product_emf_category`
        FOREIGN KEY (`emf_category_id`)
            REFERENCES `emf_products_example_app_test`.`emf_category` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
